version: '3.8'
services:

  webapp:
    build: ./frontend
    ports:
      - 3000:3000

  api:
    build: ./backend
    ports:
      - 3001:3001
    environment:
      DB_URL: mongodb://db/lvl5-mission5
    
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./lvl5-mission5:/data/db
volumes:
  lvl5-mission5:

